using System;
using System.IO;
using System.Threading.Tasks;
using MusicScope.Audio;
using MusicScope.Core;
using Xunit;

namespace MusicScope.Core.Tests;

public class FfmpegDecoderTests
{
    [Fact]
    public async Task FfmpegDecoder_Decodes_Wav_File_And_Analyzes()
    {
        string wavPath = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "test_sine.wav"));
        if (!File.Exists(wavPath))
        {
            wavPath = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "test_sine.wav"));
        }
        Assert.True(File.Exists(wavPath), $"Test WAV file does not exist at {wavPath}");

        var decoder = new FfmpegAudioDecoder();
        var probe = await decoder.ProbeAsync(wavPath);

        Assert.Equal(44100.0, probe.SampleRate);
        Assert.Equal(2, probe.ChannelCount);
        Assert.InRange(probe.Duration.TotalSeconds, 0.9, 1.1);

        var engine = new AudioAnalysisEngine(probe.SampleRate, probe.ChannelCount);

        long samplesReceived = 0;
        await decoder.DecodeAsync(wavPath, (chunk, channels, sampleRate, progress) =>
        {
            samplesReceived += chunk.Length;
            engine.ProcessAudioBlock(chunk.Span);
            return Task.CompletedTask;
        });

        Assert.True(samplesReceived >= 88000, $"Expected >= 88000 samples, got {samplesReceived}");

        var report = engine.GenerateReport("Test Sine 1kHz", wavPath, probe.FormatName, probe.Duration);

        Assert.True(report.Loudness.HasAudibleSignal);
        // test_sine.wav was generated by ffmpeg with default amplitude ~ -21 dBFS
        Assert.InRange(report.Loudness.IntegratedLoudness, -22.5, -20.0);
        Assert.InRange(report.Levels.SamplePeakLeftDb, -22.5, -20.0);
        Assert.Equal(1.0, report.Stereo.Correlation, 0.05);
    }
}
