/*
 * Decompiled with CFR 0.152.
 */
package 83nnfii93jksoiow9;

import 83nnfii93jksoiow9.DetailedTrackModel;
import 83nnfii93jksoiow9.DetailedAlbumModel;
import 83nnfii93jksoiow9.TrackMeasurementModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;

public class DetailedTrackView
extends JPanel {
    private static final String INavigationControlListener = "%s dB";
    private DetailedTrackModel.INavigationControlListener LraControl;
    private DetailedAlbumModel.LraControl NavigationControl;
    private JLabel GenericSearchController;
    private JLabel GenericSearchField;
    private JLabel GenericSearchPanel;
    private JTextArea SearchItem;
    private JPanel SearchItemPanel;
    private JLabel TabCloseListener;
    private JLabel TabController;
    private JLabel TabHeaderPanel;
    private JLabel TabbedSearchView;
    private JLabel AbstractTableView;
    private JLabel AnnotatedTableView;
    private JLabel ColumnItem;
    private JLabel GenericTableView;
    private Box.Filler ITableItemClickedListener;
    private Box.Filler TableColumn;
    private Box.Filler AlbumOverviewViewController;
    private Box.Filler AlbumSearchViewController;
    private Box.Filler ArtistAlbumsViewController;
    private Box.Filler ArtistSearchViewController;
    private Box.Filler BaseSearchViewController;
    private Box.Filler BaseViewController;
    private Box.Filler DetailedAlbumViewController;
    private JLabel DetailedTrackViewController;
    private JLabel ILoadingCompletedCallback;
    private JPanel INavigationListener;
    private JPanel IViewLoader;
    private JPanel TrackSearchViewCrontroller;
    private JPanel UserAlbumsViewController;
    private JLabel UserSearchViewController;
    private JLabel UserSettingsController;
    private JScrollPane ViewManager;
    private JSeparator MainFrame;
    private JSeparator Icon;
    private JLabel AlbumOverviewView;
    private JLabel AlbumSearchView;
    private JLabel ArtistAlbumsView;
    private JLabel ArtistSearchView;
    private JLabel DetailedAlbumView;
    private JLabel DetailedTrackView;
    private JLabel ILoadMoreActionListener;
    private JLabel ISearchActionListener;
    private JLabel TrackSearchView;
    private JLabel UserAlbumsView;
    private JPanel UserSearchView;
    private JPanel UserSettingsView;
    private JPanel CountedExecutor;
    private JLabel IExecutorStateChangedListener;
    private JLabel SingleExecutor;
    private JLabel SortedList;
    private JLabel ErrorModel;
    private JLabel MessageModel;
    private JLabel ResponseModel;
    private JLabel AlbumMeasurementModel;
    private JLabel AlbumModel;
    private JLabel ArtistModel;
    private JLabel BaseModel;
    private JPanel BitDepthModel;
    private JPanel CodecModel;
    private JPanel ComposerModel;
    private JLabel CountModel;
    private JLabel GenreModel;
    private JLabel LabelModel;
    private JLabel SampleRateModel;
    private JLabel SourceModel;
    private JPanel TrackMeasurementModel;
    private JLabel TrackModel;
    private JLabel UserModel;
    private JLabel DetailedAlbumMesurementModel;
    private JPanel DetailedAlbumModel;

    public DetailedTrackView() {
        this.NavigationControl();
    }

    public void INavigationControlListener(DetailedTrackModel.INavigationControlListener detailedTrackModel) {
        this.LraControl = detailedTrackModel;
        this.LraControl();
    }

    public void INavigationControlListener(DetailedAlbumModel.LraControl detailedAlbumModel) {
        this.NavigationControl = detailedAlbumModel;
        this.INavigationControlListener();
    }

    private void INavigationControlListener() {
        this.GenericSearchField.setText(this.NavigationControl.AnnotatedTableView());
    }

    private void LraControl() {
        this.SearchItem.setText(this.LraControl.NavigationControl());
        this.TrackModel.setText(this.LraControl.TabController());
        this.UserAlbumsView.setText(String.format(INavigationControlListener, this.LraControl.AbstractTableView()));
        this.GenericTableView.setText(this.LraControl.TabbedSearchView());
        this.ILoadingCompletedCallback.setText(this.LraControl.AnnotatedTableView());
        this.TabController.setText(this.LraControl.ColumnItem());
        TrackMeasurementModel measurementModel = this.LraControl.INavigationControlListener().get(0).INavigationControlListener();
        this.INavigationControlListener(this.ArtistSearchView, INavigationControlListener, measurementModel.NavigationControl());
        this.INavigationControlListener(this.BaseModel, INavigationControlListener, measurementModel.GenericSearchController());
        this.INavigationControlListener(this.ErrorModel, INavigationControlListener, measurementModel.GenericSearchField());
        this.INavigationControlListener(this.SampleRateModel, INavigationControlListener, measurementModel.SearchItem());
        this.INavigationControlListener(this.AlbumSearchView, INavigationControlListener, measurementModel.SearchItemPanel());
        this.INavigationControlListener(this.AlbumModel, INavigationControlListener, measurementModel.TabCloseListener());
        this.INavigationControlListener(this.SingleExecutor, INavigationControlListener, measurementModel.TabController());
        this.INavigationControlListener(this.GenreModel, INavigationControlListener, measurementModel.TabHeaderPanel());
        this.UserSettingsController.setText(String.format(INavigationControlListener, measurementModel.TabbedSearchView()));
        this.ISearchActionListener.setText(String.format(INavigationControlListener, measurementModel.AbstractTableView()));
        this.DetailedTrackView.setText(String.format(INavigationControlListener, measurementModel.AnnotatedTableView()));
        this.ResponseModel.setText(String.format(INavigationControlListener, measurementModel.ColumnItem()));
        this.AnnotatedTableView.setText(String.format(INavigationControlListener, measurementModel.ITableItemClickedListener()));
        this.TabbedSearchView.setText("" + this.LraControl.GenericSearchField());
        this.DetailedAlbumMesurementModel.setText(this.LraControl.SearchItem());
    }

    private void INavigationControlListener(JLabel label, String format, Double value) {
        if (value > 0.0) {
            label.setForeground(Color.RED.darker());
        } else {
            label.setForeground(Color.BLACK);
        }
        label.setText(String.format(format, value));
    }

    private void NavigationControl() {
        this.BitDepthModel = new JPanel();
        this.TrackMeasurementModel = new JPanel();
        this.SourceModel = new JLabel();
        this.BaseSearchViewController = new Box.Filler(new Dimension(25, 0), new Dimension(25, 0), new Dimension(25, Short.MAX_VALUE));
        this.TrackModel = new JLabel();
        this.CodecModel = new JPanel();
        this.Icon = new JSeparator();
        this.DetailedAlbumModel = new JPanel();
        this.INavigationListener = new JPanel();
        this.TrackSearchViewCrontroller = new JPanel();
        this.IViewLoader = new JPanel();
        this.GenericSearchController = new JLabel();
        this.DetailedTrackViewController = new JLabel();
        this.ColumnItem = new JLabel();
        this.TabCloseListener = new JLabel();
        this.UserAlbumsViewController = new JPanel();
        this.GenericSearchField = new JLabel();
        this.ILoadingCompletedCallback = new JLabel();
        this.GenericTableView = new JLabel();
        this.TabController = new JLabel();
        this.SearchItemPanel = new JPanel();
        this.GenericSearchPanel = new JLabel();
        this.ViewManager = new JScrollPane();
        this.SearchItem = new JTextArea();
        this.UserSettingsView = new JPanel();
        this.UserSearchView = new JPanel();
        this.TrackSearchView = new JLabel();
        this.ITableItemClickedListener = new Box.Filler(new Dimension(0, 15), new Dimension(0, 15), new Dimension(Short.MAX_VALUE, 15));
        this.ArtistAlbumsView = new JLabel();
        this.ArtistModel = new JLabel();
        this.SortedList = new JLabel();
        this.LabelModel = new JLabel();
        this.BaseViewController = new Box.Filler(new Dimension(0, 15), new Dimension(0, 15), new Dimension(Short.MAX_VALUE, 15));
        this.AlbumOverviewView = new JLabel();
        this.AlbumMeasurementModel = new JLabel();
        this.IExecutorStateChangedListener = new JLabel();
        this.CountModel = new JLabel();
        this.DetailedAlbumViewController = new Box.Filler(new Dimension(0, 15), new Dimension(0, 15), new Dimension(Short.MAX_VALUE, 15));
        this.UserSearchViewController = new JLabel();
        this.DetailedAlbumView = new JLabel();
        this.ILoadMoreActionListener = new JLabel();
        this.MessageModel = new JLabel();
        this.AbstractTableView = new JLabel();
        this.ArtistAlbumsViewController = new Box.Filler(new Dimension(0, 15), new Dimension(0, 15), new Dimension(Short.MAX_VALUE, 15));
        this.TabHeaderPanel = new JLabel();
        this.UserModel = new JLabel();
        this.CountedExecutor = new JPanel();
        this.UserAlbumsView = new JLabel();
        this.TableColumn = new Box.Filler(new Dimension(0, 15), new Dimension(0, 15), new Dimension(Short.MAX_VALUE, 15));
        this.ArtistSearchView = new JLabel();
        this.BaseModel = new JLabel();
        this.ErrorModel = new JLabel();
        this.SampleRateModel = new JLabel();
        this.AlbumOverviewViewController = new Box.Filler(new Dimension(0, 15), new Dimension(0, 15), new Dimension(Short.MAX_VALUE, 15));
        this.AlbumSearchView = new JLabel();
        this.AlbumModel = new JLabel();
        this.SingleExecutor = new JLabel();
        this.GenreModel = new JLabel();
        this.AlbumSearchViewController = new Box.Filler(new Dimension(0, 15), new Dimension(0, 15), new Dimension(Short.MAX_VALUE, 15));
        this.UserSettingsController = new JLabel();
        this.DetailedTrackView = new JLabel();
        this.ISearchActionListener = new JLabel();
        this.ResponseModel = new JLabel();
        this.AnnotatedTableView = new JLabel();
        this.ArtistSearchViewController = new Box.Filler(new Dimension(0, 15), new Dimension(0, 15), new Dimension(Short.MAX_VALUE, 15));
        this.TabbedSearchView = new JLabel();
        this.DetailedAlbumMesurementModel = new JLabel();
        this.ComposerModel = new JPanel();
        this.MainFrame = new JSeparator();
        this.TrackMeasurementModel.setMaximumSize(new Dimension(5150, 14));
        this.TrackMeasurementModel.setMinimumSize(new Dimension(123, 14));
        this.TrackMeasurementModel.setName("");
        this.TrackMeasurementModel.setPreferredSize(new Dimension(124, 14));
        this.TrackMeasurementModel.setLayout(new BoxLayout(this.TrackMeasurementModel, 2));
        this.SourceModel.setText("Title:");
        this.TrackMeasurementModel.add(this.SourceModel);
        this.TrackMeasurementModel.add(this.BaseSearchViewController);
        this.TrackModel.setMaximumSize(new Dimension(5000, 18));
        this.TrackModel.setMinimumSize(new Dimension(100, 18));
        this.TrackModel.setPreferredSize(new Dimension(100, 18));
        this.TrackMeasurementModel.add(this.TrackModel);
        GroupLayout seperatorHPanelLayout = new GroupLayout(this.CodecModel);
        this.CodecModel.setLayout(seperatorHPanelLayout);
        seperatorHPanelLayout.setHorizontalGroup(seperatorHPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.Icon, GroupLayout.Alignment.TRAILING));
        seperatorHPanelLayout.setVerticalGroup(seperatorHPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(seperatorHPanelLayout.createSequentialGroup().addContainerGap().addComponent(this.Icon, -2, -1, -2).addContainerGap(-1, Short.MAX_VALUE)));
        this.IViewLoader.setLayout(new BoxLayout(this.IViewLoader, 1));
        this.GenericSearchController.setText("Album:");
        this.GenericSearchController.setMaximumSize(new Dimension(5000, 18));
        this.GenericSearchController.setMinimumSize(new Dimension(23, 18));
        this.IViewLoader.add(this.GenericSearchController);
        this.DetailedTrackViewController.setText("Genre:");
        this.DetailedTrackViewController.setMaximumSize(new Dimension(5000, 18));
        this.DetailedTrackViewController.setMinimumSize(new Dimension(23, 18));
        this.IViewLoader.add(this.DetailedTrackViewController);
        this.ColumnItem.setText("Duration:");
        this.ColumnItem.setMaximumSize(new Dimension(5000, 18));
        this.ColumnItem.setMinimumSize(new Dimension(23, 18));
        this.IViewLoader.add(this.ColumnItem);
        this.TabCloseListener.setText("Composer:");
        this.TabCloseListener.setMaximumSize(new Dimension(5000, 18));
        this.TabCloseListener.setMinimumSize(new Dimension(23, 18));
        this.IViewLoader.add(this.TabCloseListener);
        this.UserAlbumsViewController.setPreferredSize(new Dimension(200, 0));
        this.UserAlbumsViewController.setLayout(new BoxLayout(this.UserAlbumsViewController, 1));
        this.GenericSearchField.setMaximumSize(new Dimension(5000, 18));
        this.GenericSearchField.setMinimumSize(new Dimension(100, 18));
        this.GenericSearchField.setPreferredSize(new Dimension(100, 18));
        this.UserAlbumsViewController.add(this.GenericSearchField);
        this.ILoadingCompletedCallback.setMaximumSize(new Dimension(5000, 18));
        this.ILoadingCompletedCallback.setMinimumSize(new Dimension(100, 18));
        this.ILoadingCompletedCallback.setPreferredSize(new Dimension(100, 18));
        this.UserAlbumsViewController.add(this.ILoadingCompletedCallback);
        this.GenericTableView.setMaximumSize(new Dimension(5000, 18));
        this.GenericTableView.setMinimumSize(new Dimension(100, 18));
        this.GenericTableView.setPreferredSize(new Dimension(100, 18));
        this.UserAlbumsViewController.add(this.GenericTableView);
        this.TabController.setMaximumSize(new Dimension(5000, 18));
        this.TabController.setMinimumSize(new Dimension(100, 18));
        this.TabController.setPreferredSize(new Dimension(100, 18));
        this.UserAlbumsViewController.add(this.TabController);
        GroupLayout infoPanelLayout = new GroupLayout(this.TrackSearchViewCrontroller);
        this.TrackSearchViewCrontroller.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(infoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(infoPanelLayout.createSequentialGroup().addComponent(this.IViewLoader, -2, -1, -2).addGap(15, 15, 15).addComponent(this.UserAlbumsViewController, -1, 221, Short.MAX_VALUE)));
        infoPanelLayout.setVerticalGroup(infoPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.IViewLoader, -1, 72, Short.MAX_VALUE).addComponent(this.UserAlbumsViewController, -1, -1, Short.MAX_VALUE));
        this.GenericSearchPanel.setText("Artists:");
        this.GenericSearchPanel.setVerticalAlignment(1);
        this.ViewManager.setBorder(null);
        this.SearchItem.setEditable(false);
        this.SearchItem.setBackground(this.DetailedAlbumModel.getBackground());
        this.SearchItem.setColumns(20);
        this.SearchItem.setFont(this.GenericSearchPanel.getFont());
        this.SearchItem.setLineWrap(true);
        this.SearchItem.setRows(5);
        this.SearchItem.setWrapStyleWord(true);
        this.SearchItem.setMargin(new Insets(2, 0, 2, 2));
        this.ViewManager.setViewportView(this.SearchItem);
        GroupLayout artistsPanelLayout = new GroupLayout(this.SearchItemPanel);
        this.SearchItemPanel.setLayout(artistsPanelLayout);
        artistsPanelLayout.setHorizontalGroup(artistsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.GenericSearchPanel, -1, -1, Short.MAX_VALUE).addComponent(this.ViewManager));
        artistsPanelLayout.setVerticalGroup(artistsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(artistsPanelLayout.createSequentialGroup().addComponent(this.GenericSearchPanel).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.ViewManager, -1, 281, Short.MAX_VALUE)));
        GroupLayout infoArtistPanelLayout = new GroupLayout(this.INavigationListener);
        this.INavigationListener.setLayout(infoArtistPanelLayout);
        infoArtistPanelLayout.setHorizontalGroup(infoArtistPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.SearchItemPanel, GroupLayout.Alignment.TRAILING, -1, -1, Short.MAX_VALUE).addComponent(this.TrackSearchViewCrontroller, -1, -1, Short.MAX_VALUE));
        infoArtistPanelLayout.setVerticalGroup(infoArtistPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(infoArtistPanelLayout.createSequentialGroup().addComponent(this.TrackSearchViewCrontroller, -2, -1, -2).addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED).addComponent(this.SearchItemPanel, -1, -1, Short.MAX_VALUE)));
        this.UserSettingsView.setPreferredSize(new Dimension(300, 384));
        this.UserSearchView.setPreferredSize(new Dimension(200, 270));
        this.UserSearchView.setLayout(new BoxLayout(this.UserSearchView, 1));
        this.TrackSearchView.setText("LRA:");
        this.TrackSearchView.setVerticalAlignment(1);
        this.TrackSearchView.setMaximumSize(new Dimension(5000, 18));
        this.TrackSearchView.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.TrackSearchView);
        this.UserSearchView.add(this.ITableItemClickedListener);
        this.ArtistAlbumsView.setText("Left TPL:");
        this.ArtistAlbumsView.setVerticalAlignment(1);
        this.ArtistAlbumsView.setMaximumSize(new Dimension(5000, 18));
        this.ArtistAlbumsView.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.ArtistAlbumsView);
        this.ArtistModel.setText("Right TPL:");
        this.ArtistModel.setVerticalAlignment(1);
        this.ArtistModel.setMaximumSize(new Dimension(5000, 18));
        this.ArtistModel.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.ArtistModel);
        this.SortedList.setText("Mid TPL:");
        this.SortedList.setVerticalAlignment(1);
        this.SortedList.setMaximumSize(new Dimension(5000, 18));
        this.SortedList.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.SortedList);
        this.LabelModel.setText("Side TPL:");
        this.LabelModel.setVerticalAlignment(1);
        this.LabelModel.setMaximumSize(new Dimension(5000, 18));
        this.LabelModel.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.LabelModel);
        this.UserSearchView.add(this.BaseViewController);
        this.AlbumOverviewView.setText("Left RMS:");
        this.AlbumOverviewView.setVerticalAlignment(1);
        this.AlbumOverviewView.setMaximumSize(new Dimension(5000, 18));
        this.AlbumOverviewView.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.AlbumOverviewView);
        this.AlbumMeasurementModel.setText("Right RMS:");
        this.AlbumMeasurementModel.setVerticalAlignment(1);
        this.AlbumMeasurementModel.setMaximumSize(new Dimension(5000, 18));
        this.AlbumMeasurementModel.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.AlbumMeasurementModel);
        this.IExecutorStateChangedListener.setText("Mid RMS:");
        this.IExecutorStateChangedListener.setVerticalAlignment(1);
        this.IExecutorStateChangedListener.setMaximumSize(new Dimension(5000, 18));
        this.IExecutorStateChangedListener.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.IExecutorStateChangedListener);
        this.CountModel.setText("Side RMS:");
        this.CountModel.setVerticalAlignment(1);
        this.CountModel.setMaximumSize(new Dimension(5000, 18));
        this.CountModel.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.CountModel);
        this.UserSearchView.add(this.DetailedAlbumViewController);
        this.UserSearchViewController.setText("Integrated Loudness:");
        this.UserSearchViewController.setVerticalAlignment(1);
        this.UserSearchViewController.setMaximumSize(new Dimension(5000, 18));
        this.UserSearchViewController.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.UserSearchViewController);
        this.DetailedAlbumView.setText("Loudness Momentary Max:");
        this.DetailedAlbumView.setVerticalAlignment(1);
        this.DetailedAlbumView.setMaximumSize(new Dimension(5000, 18));
        this.DetailedAlbumView.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.DetailedAlbumView);
        this.ILoadMoreActionListener.setText("Loudness Short Term Max:");
        this.ILoadMoreActionListener.setVerticalAlignment(1);
        this.ILoadMoreActionListener.setMaximumSize(new Dimension(5000, 18));
        this.ILoadMoreActionListener.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.ILoadMoreActionListener);
        this.MessageModel.setText("PLR Average:");
        this.MessageModel.setVerticalAlignment(1);
        this.MessageModel.setMaximumSize(new Dimension(5000, 18));
        this.MessageModel.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.MessageModel);
        this.AbstractTableView.setText("Crest Average:");
        this.AbstractTableView.setVerticalAlignment(1);
        this.AbstractTableView.setMaximumSize(new Dimension(5000, 18));
        this.AbstractTableView.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.AbstractTableView);
        this.UserSearchView.add(this.ArtistAlbumsViewController);
        this.TabHeaderPanel.setText("Number of Confirmations:");
        this.TabHeaderPanel.setVerticalAlignment(1);
        this.TabHeaderPanel.setMaximumSize(new Dimension(5000, 18));
        this.TabHeaderPanel.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.TabHeaderPanel);
        this.UserModel.setText("First uploaded by:");
        this.UserModel.setVerticalAlignment(1);
        this.UserModel.setMaximumSize(new Dimension(5000, 18));
        this.UserModel.setMinimumSize(new Dimension(23, 18));
        this.UserSearchView.add(this.UserModel);
        this.CountedExecutor.setMinimumSize(new Dimension(100, 279));
        this.CountedExecutor.setPreferredSize(new Dimension(100, 45));
        this.CountedExecutor.setLayout(new BoxLayout(this.CountedExecutor, 1));
        this.UserAlbumsView.setHorizontalAlignment(4);
        this.UserAlbumsView.setToolTipText("");
        this.UserAlbumsView.setVerticalAlignment(1);
        this.UserAlbumsView.setHorizontalTextPosition(4);
        this.UserAlbumsView.setMaximumSize(new Dimension(5000, 18));
        this.UserAlbumsView.setMinimumSize(new Dimension(50, 18));
        this.CountedExecutor.add(this.UserAlbumsView);
        this.CountedExecutor.add(this.TableColumn);
        this.ArtistSearchView.setHorizontalAlignment(4);
        this.ArtistSearchView.setVerticalAlignment(1);
        this.ArtistSearchView.setHorizontalTextPosition(4);
        this.ArtistSearchView.setMaximumSize(new Dimension(5000, 18));
        this.ArtistSearchView.setMinimumSize(new Dimension(30, 18));
        this.CountedExecutor.add(this.ArtistSearchView);
        this.BaseModel.setHorizontalAlignment(4);
        this.BaseModel.setVerticalAlignment(1);
        this.BaseModel.setHorizontalTextPosition(4);
        this.BaseModel.setMaximumSize(new Dimension(5000, 18));
        this.BaseModel.setMinimumSize(new Dimension(30, 18));
        this.CountedExecutor.add(this.BaseModel);
        this.ErrorModel.setHorizontalAlignment(4);
        this.ErrorModel.setVerticalAlignment(1);
        this.ErrorModel.setHorizontalTextPosition(4);
        this.ErrorModel.setMaximumSize(new Dimension(5000, 18));
        this.ErrorModel.setMinimumSize(new Dimension(30, 18));
        this.CountedExecutor.add(this.ErrorModel);
        this.SampleRateModel.setHorizontalAlignment(4);
        this.SampleRateModel.setVerticalAlignment(1);
        this.SampleRateModel.setHorizontalTextPosition(4);
        this.SampleRateModel.setMaximumSize(new Dimension(5000, 18));
        this.SampleRateModel.setMinimumSize(new Dimension(30, 18));
        this.CountedExecutor.add(this.SampleRateModel);
        this.CountedExecutor.add(this.AlbumOverviewViewController);
        this.AlbumSearchView.setHorizontalAlignment(4);
        this.AlbumSearchView.setVerticalAlignment(1);
        this.AlbumSearchView.setHorizontalTextPosition(4);
        this.AlbumSearchView.setMaximumSize(new Dimension(5000, 18));
        this.AlbumSearchView.setMinimumSize(new Dimension(30, 18));
        this.CountedExecutor.add(this.AlbumSearchView);
        this.AlbumModel.setHorizontalAlignment(4);
        this.AlbumModel.setVerticalAlignment(1);
        this.AlbumModel.setHorizontalTextPosition(4);
        this.AlbumModel.setMaximumSize(new Dimension(5000, 18));
        this.AlbumModel.setMinimumSize(new Dimension(30, 18));
        this.CountedExecutor.add(this.AlbumModel);
        this.SingleExecutor.setHorizontalAlignment(4);
        this.SingleExecutor.setVerticalAlignment(1);
        this.SingleExecutor.setHorizontalTextPosition(4);
        this.SingleExecutor.setMaximumSize(new Dimension(5000, 18));
        this.SingleExecutor.setMinimumSize(new Dimension(30, 18));
        this.CountedExecutor.add(this.SingleExecutor);
        this.GenreModel.setHorizontalAlignment(4);
        this.GenreModel.setVerticalAlignment(1);
        this.GenreModel.setHorizontalTextPosition(4);
        this.GenreModel.setMaximumSize(new Dimension(5000, 18));
        this.GenreModel.setMinimumSize(new Dimension(30, 18));
        this.CountedExecutor.add(this.GenreModel);
        this.CountedExecutor.add(this.AlbumSearchViewController);
        this.UserSettingsController.setHorizontalAlignment(4);
        this.UserSettingsController.setVerticalAlignment(1);
        this.UserSettingsController.setHorizontalTextPosition(4);
        this.UserSettingsController.setMaximumSize(new Dimension(5000, 18));
        this.UserSettingsController.setMinimumSize(new Dimension(30, 18));
        this.CountedExecutor.add(this.UserSettingsController);
        this.DetailedTrackView.setHorizontalAlignment(4);
        this.DetailedTrackView.setVerticalAlignment(1);
        this.DetailedTrackView.setHorizontalTextPosition(4);
        this.DetailedTrackView.setMaximumSize(new Dimension(5000, 18));
        this.DetailedTrackView.setMinimumSize(new Dimension(30, 18));
        this.CountedExecutor.add(this.DetailedTrackView);
        this.ISearchActionListener.setHorizontalAlignment(4);
        this.ISearchActionListener.setVerticalAlignment(1);
        this.ISearchActionListener.setHorizontalTextPosition(4);
        this.ISearchActionListener.setMaximumSize(new Dimension(5000, 18));
        this.ISearchActionListener.setMinimumSize(new Dimension(40, 18));
        this.CountedExecutor.add(this.ISearchActionListener);
        this.ResponseModel.setHorizontalAlignment(4);
        this.ResponseModel.setVerticalAlignment(1);
        this.ResponseModel.setHorizontalTextPosition(4);
        this.ResponseModel.setMaximumSize(new Dimension(5000, 18));
        this.ResponseModel.setMinimumSize(new Dimension(30, 18));
        this.CountedExecutor.add(this.ResponseModel);
        this.AnnotatedTableView.setHorizontalAlignment(4);
        this.AnnotatedTableView.setVerticalAlignment(1);
        this.AnnotatedTableView.setHorizontalTextPosition(4);
        this.AnnotatedTableView.setMaximumSize(new Dimension(5000, 18));
        this.AnnotatedTableView.setMinimumSize(new Dimension(30, 18));
        this.CountedExecutor.add(this.AnnotatedTableView);
        this.CountedExecutor.add(this.ArtistSearchViewController);
        this.TabbedSearchView.setHorizontalAlignment(4);
        this.TabbedSearchView.setVerticalAlignment(1);
        this.TabbedSearchView.setHorizontalTextPosition(4);
        this.TabbedSearchView.setMaximumSize(new Dimension(5000, 18));
        this.TabbedSearchView.setMinimumSize(new Dimension(30, 18));
        this.CountedExecutor.add(this.TabbedSearchView);
        this.DetailedAlbumMesurementModel.setHorizontalAlignment(4);
        this.DetailedAlbumMesurementModel.setVerticalAlignment(1);
        this.DetailedAlbumMesurementModel.setHorizontalTextPosition(4);
        this.DetailedAlbumMesurementModel.setMaximumSize(new Dimension(5000, 18));
        this.DetailedAlbumMesurementModel.setMinimumSize(new Dimension(30, 18));
        this.CountedExecutor.add(this.DetailedAlbumMesurementModel);
        GroupLayout measurementPanelLayout = new GroupLayout(this.UserSettingsView);
        this.UserSettingsView.setLayout(measurementPanelLayout);
        measurementPanelLayout.setHorizontalGroup(measurementPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(measurementPanelLayout.createSequentialGroup().addComponent(this.UserSearchView, -2, -1, -2).addGap(15, 15, 15).addComponent(this.CountedExecutor, -1, 121, Short.MAX_VALUE)));
        measurementPanelLayout.setVerticalGroup(measurementPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.CountedExecutor, -1, -1, Short.MAX_VALUE).addComponent(this.UserSearchView, -1, 384, Short.MAX_VALUE));
        this.ComposerModel.setPreferredSize(new Dimension(50, 32));
        this.MainFrame.setOrientation(1);
        GroupLayout seperatorVPanelLayout = new GroupLayout(this.ComposerModel);
        this.ComposerModel.setLayout(seperatorVPanelLayout);
        seperatorVPanelLayout.setHorizontalGroup(seperatorVPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(seperatorVPanelLayout.createSequentialGroup().addContainerGap(21, Short.MAX_VALUE).addComponent(this.MainFrame, -2, -1, -2).addContainerGap(21, Short.MAX_VALUE)));
        seperatorVPanelLayout.setVerticalGroup(seperatorVPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(seperatorVPanelLayout.createSequentialGroup().addGap(0, 0, 0).addComponent(this.MainFrame).addGap(0, 0, 0)));
        GroupLayout valuePanelLayout = new GroupLayout(this.DetailedAlbumModel);
        this.DetailedAlbumModel.setLayout(valuePanelLayout);
        valuePanelLayout.setHorizontalGroup(valuePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(valuePanelLayout.createSequentialGroup().addComponent(this.INavigationListener, -1, -1, Short.MAX_VALUE).addGap(0, 0, 0).addComponent(this.ComposerModel, -2, 44, -2).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED).addComponent(this.UserSettingsView, -2, 336, -2).addContainerGap()));
        valuePanelLayout.setVerticalGroup(valuePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.UserSettingsView, GroupLayout.Alignment.TRAILING, -1, -1, Short.MAX_VALUE).addComponent(this.ComposerModel, GroupLayout.Alignment.TRAILING, -1, 384, Short.MAX_VALUE).addComponent(this.INavigationListener, -1, -1, Short.MAX_VALUE));
        GroupLayout rootPanelLayout = new GroupLayout(this.BitDepthModel);
        this.BitDepthModel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(rootPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(rootPanelLayout.createSequentialGroup().addGap(0, 0, 0).addGroup(rootPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(this.DetailedAlbumModel, -1, -1, Short.MAX_VALUE).addComponent(this.TrackMeasurementModel, -1, -1, Short.MAX_VALUE).addComponent(this.CodecModel, -1, -1, Short.MAX_VALUE))));
        rootPanelLayout.setVerticalGroup(rootPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(rootPanelLayout.createSequentialGroup().addComponent(this.TrackMeasurementModel, -2, -1, -2).addGap(0, 0, 0).addComponent(this.CodecModel, -2, -1, -2).addGap(0, 0, 0).addComponent(this.DetailedAlbumModel, -1, -1, Short.MAX_VALUE).addGap(0, 0, 0)));
        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(this.BitDepthModel, -1, -1, Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(this.BitDepthModel, -1, -1, Short.MAX_VALUE).addContainerGap()));
    }
}

