/*
 * Decompiled with CFR 0.152.
 */
package sdfgjkljljoftrytrszgijpokjprs;

import com.xivero.hraa.Main;
import java.io.File;
import java.lang.reflect.AccessibleObject;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import sdfgjkljljoftrytrszgijpokjprs.IValueComposer;
import sdfgjkljljoftrytrszgijpokjprs.ReportingController;
import sdfgjkljljoftrytrszgijpokjprs.IMetaInformationListener;
import sdfgjkljljoftrytrszgijpokjprs.ValueModel;
import sdfgjkljljoftrytrszgijpokjprs.IAudioMetaInformation;
import sdfgjkljljoftrytrszgijpokjprs.ReportingParameter;
import sdfgjkljljoftrytrszgijpokjprs.ILevelMeterControlMidSideSwitch;
import sdfgjkljljoftrytrszgijpokjprs.IValueReporting;
import sdfgjkljljoftrytrszgijpokjprs.ITrackLoadedListener;

public class SimpleValueComposer
implements IValueComposer,
IMetaInformationListener,
ILevelMeterControlMidSideSwitch,
ITrackLoadedListener {
    private IAudioMetaInformation DSP;
    private final Locale FFT = new Locale("en", "us");
    private boolean responseView;
    private File AdditionalMetadataValue;

    @Override
    public StringBuilder FFT(ReportingController fiypGaFYdzscEBybnfTNrMU) {
        ArrayList<AbstractMap.SimpleEntry<String, Object>> arrayList = new ArrayList<AbstractMap.SimpleEntry<String, Object>>(0);
        for (IValueReporting<?> oJKdRGEwipDKnLCbDZfxxHL2 : fiypGaFYdzscEBybnfTNrMU.FFT()) {
            Object object;
            String[] stringArray;
            String string;
            String string2;
            ReportingParameter fegnCROFfntWhihpSdONLyP2;
            Object obj = oJKdRGEwipDKnLCbDZfxxHL2.AudioFileExtension();
            if (obj == null) continue;
            Class<?> clazz = obj.getClass();
            Field[] fieldArray = clazz.getDeclaredFields();
            Method[] methodArray = clazz.getDeclaredMethods();
            for (Field field : fieldArray) {
                fegnCROFfntWhihpSdONLyP2 = field.getAnnotation(ReportingParameter.class);
                if (fegnCROFfntWhihpSdONLyP2 == null || !fegnCROFfntWhihpSdONLyP2.AdditionalMetadataValue() || this.responseView && fegnCROFfntWhihpSdONLyP2.AudioFileExtension()) continue;
                string2 = fegnCROFfntWhihpSdONLyP2.DSP();
                string = fegnCROFfntWhihpSdONLyP2.FFT();
                stringArray = fegnCROFfntWhihpSdONLyP2.responseView();
                field.setAccessible(true);
                if (Arrays.asList(stringArray).contains(this.DSP.MetaInfomationCopy().FFT().toString())) continue;
                try {
                    object = field.get(obj);
                    arrayList.add(new AbstractMap.SimpleEntry<String, ValueModel>(string2, new ValueModel(object, string)));
                }
                catch (IllegalAccessException | IllegalArgumentException exception) {
                    // empty catch block
                }
            }
            for (AccessibleObject accessibleObject : methodArray) {
                fegnCROFfntWhihpSdONLyP2 = ((Method)accessibleObject).getAnnotation(ReportingParameter.class);
                if (fegnCROFfntWhihpSdONLyP2 == null) continue;
                string2 = fegnCROFfntWhihpSdONLyP2.DSP();
                string = fegnCROFfntWhihpSdONLyP2.FFT();
                stringArray = fegnCROFfntWhihpSdONLyP2.responseView();
                accessibleObject.setAccessible(true);
                if (Arrays.asList(stringArray).contains(this.DSP.MetaInfomationCopy().FFT().toString())) continue;
                try {
                    object = ((Method)accessibleObject).invoke(obj, new Object[0]);
                    arrayList.add(new AbstractMap.SimpleEntry<String, ValueModel>(string2, new ValueModel(object, string)));
                }
                catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException exception) {
                    Logger.getLogger(SimpleValueComposer.class.getName()).log(Level.SEVERE, null, exception);
                }
            }
            arrayList.add(new AbstractMap.SimpleEntry<String, ValueModel>("", new ValueModel("", "")));
        }
        return this.DSP(arrayList);
    }

    private StringBuilder DSP(ArrayList<AbstractMap.SimpleEntry<String, Object>> arrayList) {
        StringBuilder stringBuilder = new StringBuilder(0);
        stringBuilder.append(String.format(this.FFT, "Report generated by the MusicScope %s - www.xivero.com", Main.DSP.FFT(2))).append(System.lineSeparator());
        stringBuilder.append(System.lineSeparator());
        stringBuilder.append(String.format(this.FFT, "%-25s %s", "File:", this.AdditionalMetadataValue.getName())).append(System.lineSeparator());
        stringBuilder.append(System.lineSeparator());
        stringBuilder.append(String.format(this.FFT, "%-25s %6s", new Object[]{"Audio format:", this.DSP.MetaInfomationCopy().FFT()})).append(System.lineSeparator());
        stringBuilder.append(String.format(this.FFT, "%-25s %6s bit", "Bit depth:", this.DSP.FFT().DSP())).append(System.lineSeparator());
        stringBuilder.append(String.format(this.FFT, "%-25s %6.1f kHz", "Sample rate:", (double)this.DSP.DSP() / 1000.0)).append(System.lineSeparator());
        stringBuilder.append(System.lineSeparator());
        this.DSP(stringBuilder);
        this.DSP(stringBuilder, arrayList);
        return stringBuilder;
    }

    private void DSP(StringBuilder stringBuilder, ArrayList<AbstractMap.SimpleEntry<String, Object>> arrayList) {
        for (AbstractMap.SimpleEntry<String, Object> simpleEntry : arrayList) {
            String string;
            ValueModel rOJuPbsRZYkDSnyfZISOUMD = (ValueModel)simpleEntry.getValue();
            if (rOJuPbsRZYkDSnyfZISOUMD.DSP() instanceof ArrayList) {
                stringBuilder.append(simpleEntry.getKey()).append(System.lineSeparator());
                this.DSP(stringBuilder, (ArrayList)rOJuPbsRZYkDSnyfZISOUMD.DSP());
                continue;
            }
            if (rOJuPbsRZYkDSnyfZISOUMD.DSP() instanceof Double) {
                double d = (Double)rOJuPbsRZYkDSnyfZISOUMD.DSP();
                string = String.format(this.FFT, "%5.1f", d);
            } else {
                string = rOJuPbsRZYkDSnyfZISOUMD.DSP().toString();
            }
            stringBuilder.append(String.format(this.FFT, "%-25s %6s %s", simpleEntry.getKey(), string, rOJuPbsRZYkDSnyfZISOUMD.FFT())).append(System.lineSeparator());
        }
    }

    private void DSP(StringBuilder stringBuilder) {
        ArrayList<String> arrayList = new ArrayList<String>(0);
        if (this.DSP.AacAudioCodec() != this.DSP.AacMetaDataModel()) {
            arrayList.add(String.format(this.FFT, "%-25s %d / %d Byte", "Chunk Inconsistency:", this.DSP.AacMetaDataModel(), this.DSP.AacAudioCodec()));
        }
        if (!arrayList.isEmpty()) {
            stringBuilder.append("File Errors:").append(System.lineSeparator());
            for (String string : arrayList) {
                stringBuilder.append(string).append(System.lineSeparator());
            }
            stringBuilder.append(System.lineSeparator());
        }
    }

    @Override
    public void DSP(IAudioMetaInformation yGjBevanihqaxYKnUNtrNeA, IAudioMetaInformation yGjBevanihqaxYKnUNtrNeA2) {
        this.DSP = yGjBevanihqaxYKnUNtrNeA2;
    }

    @Override
    public void DSP(String string) {
        this.AdditionalMetadataValue = new File(string);
    }

    @Override
    public void FFT(boolean bl) {
        this.responseView = bl;
    }
}

